
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password

    ports:
      - "3306:3306"
 
  redis:
    image: "redis:latest"
    container_name: redis_container1
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi_container1
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
