version: '3.9'

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

    

